management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles:
    active: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users

---
spring:
  profiles:
    active: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: users